name: Standard

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  standard:
    name: OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 1
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    steps:
      - name: Debug COVERALLS variable
        run: echo "COVERALLS is $COVERALLS"
        env:
          CONDA: 'false'
          COVERALLS: 'false'
          PAGES: 'true'

      - name: Show the environment variables
        if: runner.os != 'Windows'
        run: |
          echo "CONDA    = $CONDA"
          echo "COVERALLS= $COVERALLS"
          echo "PAGES    = $PAGES"

      - name: Set Timezone
        run: echo "TZ=UTC" >> $GITHUB_ENV

      - name: Checking out the repository
        uses: actions/checkout@v4

      - name: Set Locale - Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8

      - name: Set Locale - macOS
        if: runner.os == 'macOS'
        run: |
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV

      - name: Preparing scripts - Ubuntu
        if: runner.os == 'Linux'
        run: |
            sudo apt-get update && sudo apt-get install -y dos2unix
            chmod +x scripts/run_prep_*.sh
            ./scripts/run_prep_bash_scripts.sh

      - name: Preparing scripts - macOS
        if: runner.os == 'macOS'
        run: |
            brew install dos2unix
            chmod +x scripts/run_prep_*.zsh
            ./scripts/run_prep_bash_scripts.zsh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies - pipenv - prod
        if: ${{ env.CONDA != 'true' }}
        run: make pipenv-prod

      - name: Install dependencies - Conda & pipenv - prod
        if: ${{ env.CONDA == 'true' }}
        run: make conda-prod

      - name: Compile the Python code - prod
        run: make compileall

      - name: Run pytest - prod
        run: make pytest-ci

      - name: Install dependencies - pipenv - dev
        if: ${{ env.CONDA != 'true' }}
        run: make pipenv-dev

      - name: Install dependencies - Conda & pipenv - dev
        if: ${{ env.CONDA == 'true' }}
        run: make conda-dev

      - name: Run pytest - dev
        run: make isort black lint docs tests

      - name: Coveralls
        if: ${{ env.COVERALLS == 'true' && runner.os == 'Linux' }}
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
          flag-name: run-${{ matrix.os }}-py${{ matrix.python-version }}
          parallel: false
          parallel-finished: true

      - name: Deploy to GitHub Pages
        if: ${{ env.PAGES == 'true' && runner.os == 'Linux' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
